In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

In [3]:
df = pd.read_csv('dirty_cafe_sales.csv')

In [4]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [6]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [7]:
df['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [8]:
print(df[df['Item'] == 'ERROR'].shape[0])
print(df[df['Item'] == 'UNKNOWN'].shape[0])

292
344

In [9]:
df['Payment Method'].unique()

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan],
      dtype=object)

In [10]:
print(df[df['Payment Method'] == 'UNKNOWN'].shape[0])
print(df[df['Payment Method'] == 'ERROR'].shape[0])
print(df['Payment Method'].isna().sum())

293
306
2579

In [11]:
df['Payment Method'] = df['Payment Method'].replace(['UNKNOWN','ERROR'],pd.NA)
df['Payment Method'] = df['Payment Method'].fillna('Undisclosed')

In [12]:
print(df[df['Payment Method'] == 'UNKNOWN'].shape[0])
print(df[df['Payment Method'] == 'ERROR'].shape[0])
print(df['Payment Method'].isna().sum())

0
0
0

In [13]:
df['Location'].unique()

array(['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR'], dtype=object)

In [14]:
print(df[df['Location'] == 'UNKNOWN'].shape[0])
print(df[df['Location'] == 'ERROR'].shape[0])
print(df['Location'].isna().sum())

338
358
3265

In [15]:
df['Location'] = df['Location'].replace(['UNKNOWN','ERROR'],pd.NA)
df['Location'] = df['Location'].fillna('Not Given')

In [16]:
print(df[df['Location'] == 'UNKNOWN'].shape[0])
print(df[df['Location'] == 'ERROR'].shape[0])
print(df['Location'].isna().sum())

0
0
0

In [17]:
df['Transaction Date']

0       2023-09-08
1       2023-05-16
2       2023-07-19
3       2023-04-27
4       2023-06-11
           ...
9995    2023-08-30
9996    2023-06-02
9997    2023-03-02
9998    2023-12-02
9999    2023-11-07
Name: Transaction Date, Length: 10000, dtype: object

In [18]:
print(df[df['Transaction Date'] == 'UNKNOWN'].shape[0])
print(df[df['Transaction Date'] == 'ERROR'].shape[0])
print(df['Transaction Date'].isna().sum())

159
142
159

In [19]:
df['Transaction Date'] = df['Transaction Date'].replace(['ERROR', 'UNKNOWN'], pd.NA)

In [20]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors='coerce')

In [21]:
df['Transaction Date'].isna().sum()

np.int64(460)

In [22]:
df = df.dropna(subset=['Transaction Date'])

In [23]:
df['Transaction Date'].isna().sum()

np.int64(0)

In [24]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,Undisclosed,Not Given,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [25]:
df[['Quantity','Price Per Unit','Total Spent']]

     Quantity Price Per Unit Total Spent
0           2            2.0         4.0
1           4            3.0        12.0
2           4            1.0       ERROR
3           2            5.0        10.0
4           2            2.0         4.0
...       ...            ...         ...
9995        2            2.0         4.0
9996        3            NaN         3.0
9997        4            2.0         8.0
9998        3            NaN         3.0
9999        3            4.0        12.0

[9540 rows x 3 columns]

In [26]:
df['Price Per Unit'].unique()

array(['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN'],
      dtype=object)

In [27]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce').astype('Int64')
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce').astype('Float64')
df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce').astype('Float64')

C:\Users\muska\AppData\Local\Temp\ipykernel_17724\189060124.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce').astype('Int64')
C:\Users\muska\AppData\Local\Temp\ipykernel_17724\189060124.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce').astype('Float64')
C:\Users\muska\AppData\Local\Temp\ipykernel_17724\189060124.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce').astype('Float64')

In [28]:
df.dtypes

Transaction ID              object
Item                        object
Quantity                     Int64
Price Per Unit             Float64
Total Spent                Float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
dtype: object

In [29]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,<NA>,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,Undisclosed,Not Given,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [30]:
df[df['Quantity'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
20,TXN_3522028,Smoothie,<NA>,4.0,20.0,Cash,In-store,2023-04-04
55,TXN_5522862,Cookie,<NA>,1.0,2.0,Credit Card,Takeaway,2023-03-19
57,TXN_2080895,Cake,<NA>,3.0,3.0,Digital Wallet,In-store,2023-04-19
66,TXN_8501819,Juice,<NA>,3.0,6.0,Cash,Not Given,2023-03-30
117,TXN_2148617,Juice,<NA>,3.0,9.0,Digital Wallet,Not Given,2023-01-10
...,...,...,...,...,...,...,...,...
9932,TXN_8502079,Tea,<NA>,1.5,3.0,Cash,Not Given,2023-04-20
9935,TXN_9778251,Tea,<NA>,1.5,6.0,Undisclosed,Takeaway,2023-11-09
9944,TXN_7495283,Cake,<NA>,3.0,15.0,Credit Card,Takeaway,2023-04-14
9957,TXN_6487003,Coffee,<NA>,2.0,8.0,Credit Card,Takeaway,2023-11-15
9984,TXN_3142496,Smoothie,<NA>,4.0,4.0,Cash,Takeaway,2023-07-27

In [31]:
quantity_mask = df['Quantity'].isna() & df[['Price Per Unit','Total Spent']].notna().all(axis=1)
df.loc[quantity_mask,'Quantity'] = df['Total Spent'] / df['Price Per Unit']

In [32]:
df[quantity_mask]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
20,TXN_3522028,Smoothie,5,4.0,20.0,Cash,In-store,2023-04-04
55,TXN_5522862,Cookie,2,1.0,2.0,Credit Card,Takeaway,2023-03-19
57,TXN_2080895,Cake,1,3.0,3.0,Digital Wallet,In-store,2023-04-19
66,TXN_8501819,Juice,2,3.0,6.0,Cash,Not Given,2023-03-30
117,TXN_2148617,Juice,3,3.0,9.0,Digital Wallet,Not Given,2023-01-10
...,...,...,...,...,...,...,...,...
9932,TXN_8502079,Tea,2,1.5,3.0,Cash,Not Given,2023-04-20
9935,TXN_9778251,Tea,4,1.5,6.0,Undisclosed,Takeaway,2023-11-09
9944,TXN_7495283,Cake,5,3.0,15.0,Credit Card,Takeaway,2023-04-14
9957,TXN_6487003,Coffee,4,2.0,8.0,Credit Card,Takeaway,2023-11-15
9984,TXN_3142496,Smoothie,1,4.0,4.0,Cash,Takeaway,2023-07-27

In [33]:
price_per_unit_mask = df['Price Per Unit'].isna() & df[['Quantity','Total Spent']].notna().all(axis=1)
df.loc[price_per_unit_mask,'Price Per Unit'] = df['Total Spent'] / df['Quantity']

In [34]:
df[price_per_unit_mask]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
56,TXN_3578141,Cake,5,3.0,15.0,Undisclosed,Takeaway,2023-06-27
68,TXN_8427104,Salad,2,5.0,10.0,Undisclosed,In-store,2023-10-27
85,TXN_8035512,Tea,3,1.5,4.5,Cash,Not Given,2023-10-29
118,TXN_4633784,ERROR,5,3.0,15.0,Undisclosed,In-store,2023-02-06
140,TXN_2484241,Cake,3,3.0,9.0,Digital Wallet,Not Given,2023-07-19
...,...,...,...,...,...,...,...,...
9924,TXN_5981429,Juice,2,3.0,6.0,Digital Wallet,Not Given,2023-12-24
9926,TXN_2464706,Cake,4,3.0,12.0,Digital Wallet,Takeaway,2023-11-09
9961,TXN_2153100,Tea,2,1.5,3.0,Cash,Not Given,2023-12-29
9996,TXN_9659401,NaN,3,1.0,3.0,Digital Wallet,Not Given,2023-06-02
9998,TXN_7695629,Cookie,3,1.0,3.0,Digital Wallet,Not Given,2023-12-02

In [35]:
total_spent_mask = df['Total Spent'].isna() & df[['Quantity','Price Per Unit']].notna().all(axis=1)
df.loc[total_spent_mask,'Total Spent'] = df['Price Per Unit'] * df['Quantity']

In [36]:
df[total_spent_mask]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19
25,TXN_7958992,Smoothie,3,4.0,12.0,Undisclosed,Not Given,2023-12-13
31,TXN_8927252,UNKNOWN,2,1.0,2.0,Credit Card,Not Given,2023-11-06
42,TXN_6650263,Tea,2,1.5,3.0,Undisclosed,Takeaway,2023-01-10
94,TXN_6289610,Juice,3,3.0,9.0,Cash,Takeaway,2023-08-07
...,...,...,...,...,...,...,...,...
9853,TXN_9266499,Cake,1,3.0,3.0,Digital Wallet,Not Given,2023-02-16
9890,TXN_2749289,Smoothie,2,4.0,8.0,Digital Wallet,Takeaway,2023-05-05
9954,TXN_1191659,Coffee,4,2.0,8.0,Credit Card,In-store,2023-11-21
9977,TXN_5548914,Juice,2,3.0,6.0,Digital Wallet,In-store,2023-11-04
9993,TXN_4766549,Smoothie,2,4.0,8.0,Cash,Not Given,2023-10-20

In [37]:
df[df['Quantity'].isna()].shape

(36, 8)

In [38]:
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce').astype('float')
df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce')

#Filling Price per unit column by using map of item and its prices
price_map = df.groupby('Item')['Price Per Unit'].median().to_dict()
unit_price_mask = df['Price Per Unit'].isna()
df.loc[unit_price_mask, 'Price Per Unit'] = df.loc[unit_price_mask, 'Item'].map(price_map)

#Finally filling up the Quantity and Total Spent one more time since we filled up Price Per Unit more
quantity_null_mask = (df['Quantity'].isna() & df['Total Spent'].notna() & df['Price Per Unit'].notna() & (df['Price Per Unit'] != 0))
df.loc[quantity_null_mask, 'Quantity'] = (df.loc[quantity_null_mask, 'Total Spent'] / df.loc[quantity_null_mask, 'Price Per Unit'])
df['Quantity'] = df['Quantity'].round().astype('Int64')
total_spent_null_mask = (df['Total Spent'].isna() & df[['Price Per Unit', 'Quantity']].notna().all(axis=1))
df.loc[total_spent_null_mask, 'Total Spent'] = (df.loc[total_spent_null_mask, 'Quantity'] * df.loc[total_spent_null_mask, 'Price Per Unit'])

C:\Users\muska\AppData\Local\Temp\ipykernel_17724\2799346444.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')
C:\Users\muska\AppData\Local\Temp\ipykernel_17724\2799346444.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce').astype('float')
C:\Users\muska\AppData\Local\Temp\ipykernel_17724\2799346444.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce')
C:\Users\muska\AppData\Local\Temp\ipykernel_17724\2799346444.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Quantity'] = df['Quantity'].round().astype('Int64')

In [39]:
#filling item column based on prices using probability so i wont create the biased data
no_nan_items = df.dropna(subset='Item')
item_percentages = no_nan_items.groupby('Price Per Unit')['Item'].value_counts(normalize=True)
price_item_map = {}
for index in item_percentages.index.get_level_values(0).unique():
    items = item_percentages[index].index.tolist()
    percentages = item_percentages[index].values.tolist()

    price_item_map[index] = {
        'items':items,
        'probability':percentages
    }


def fill_missing(per_unit_price):
    if per_unit_price in price_item_map:
        return np.random.choice(a=price_item_map[per_unit_price]['items'], p=price_item_map[per_unit_price]['probability'])
    else:
        return np.nan
        

#applying function to each row in item column:
item_nan_mask = df['Item'].isna()
df.loc[item_nan_mask, 'Item'] = df.loc[item_nan_mask, 'Price Per Unit'].map(fill_missing)

In [40]:
df.replace(r'(?i)(\berror\b|\bunknown\b)', np.nan, regex=True, inplace=True)

C:\Users\muska\AppData\Local\Temp\ipykernel_17724\1995862488.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace(r'(?i)(\berror\b|\bunknown\b)', np.nan, regex=True, inplace=True)

In [41]:
#Droping rows with na values that cant be filled
df = df.dropna(how='any', subset=['Quantity', 'Price Per Unit', 'Total Spent'])
#Finally filling up all NA values with 'Unknown' and checking for any errors with filling up
df = df.fillna('Unknown')
(df.isna().mean() * 100).round(2)

Transaction ID      0.0
Item                0.0
Quantity            0.0
Price Per Unit      0.0
Total Spent         0.0
Payment Method      0.0
Location            0.0
Transaction Date    0.0
dtype: float64

In [42]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,Undisclosed,Not Given,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [43]:
df['Month'] = df['Transaction Date'].dt.month

In [44]:
total_per_month = df.groupby('Month')['Total Spent'].sum()

In [45]:
total_per_month

Month
1     7254.0
2     6644.0
3     7216.0
4     7179.0
5     6957.5
6     7353.0
7     6877.5
8     7092.5
9     6871.0
10    7314.0
11    6967.0
12    7195.0
Name: Total Spent, dtype: Float64

In [46]:
df['Day'] = df['Transaction Date'].dt.day

In [47]:
total_spent_per_day = df.groupby('Day')['Total Spent'].sum()

In [48]:
total_spent_per_day

Day
1     2589.5
2     2688.0
3     2522.0
4     2759.0
5     2643.0
6     3482.0
7     2896.0
8     2774.5
9     2810.0
10    2978.0
11    2464.0
12    2620.0
13    2691.5
14    2613.5
15    2867.5
16    3132.5
17    2715.5
18    2908.5
19    2755.0
20    3001.0
21    3002.5
22    2496.0
23    3036.0
24    2749.5
25    2652.5
26    2959.5
27    2470.0
28    2974.0
29    2380.0
30    2726.5
31    1563.0
Name: Total Spent, dtype: Float64

In [49]:
df.set_index('Transaction Date',inplace = True)

In [50]:
df.sort_index(inplace=True)

In [51]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Month,Day
Transaction Date,,,,,,,,,
2023-01-01,TXN_5358805,Coffee,5,2.0,10.0,Digital Wallet,Not Given,1,1
2023-01-01,TXN_2024598,Sandwich,1,4.0,4.0,Digital Wallet,In-store,1,1
2023-01-01,TXN_6234882,Cookie,4,1.0,4.0,Credit Card,Not Given,1,1
2023-01-01,TXN_6093955,Tea,5,1.5,7.5,Undisclosed,Takeaway,1,1
2023-01-01,TXN_5728991,Salad,2,5.0,10.0,Undisclosed,Not Given,1,1
...,...,...,...,...,...,...,...,...,...
2023-12-31,TXN_9027002,Smoothie,4,4.0,16.0,Credit Card,Takeaway,12,31
2023-12-31,TXN_1714348,Sandwich,2,4.0,8.0,Cash,Takeaway,12,31
2023-12-31,TXN_6380978,Tea,1,1.5,1.5,Cash,Not Given,12,31
2023-12-31,TXN_1405498,Juice,2,3.0,6.0,Undisclosed,Takeaway,12,31
2023-12-31,TXN_9469735,Cake,1,3.0,3.0,Undisclosed,In-store,12,31

In [52]:
df.to_csv('Cleaned_cafe_sales_data.csv')